### ISSUE TITLE
Chainsplits, which tip is valid?

### ISSUE THREAD

**Issue by laakie** [unobtanium-official/Unobtanium#49]
Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade.

We're synced with the explorer : https://chainz.cryptoid.info/uno/
After invalidating a block 7000 blocks lower

What's going on, what is the current correct height and why are nodes disagreeing

**Comment by Shinoa-Fores** [comment]
Perhaps knowing the version of node software would help here, could you please list. Nodes often disagree especially on small networks such as UNO but if you continue to have this issue I'd suggest ensuring you have the latest client and perform a fresh sync, since there _was_ an earlier chainsplit reported. At this time all the peers I see, including chainz, show the correct height and chain.

**Comment by Shinoa-Fores** [comment]
Block checkpointed at 1670000, upgrade node.
https://github.com/unobtanium-official/Unobtanium/commit/be7dc97dcf294cd1b2ece34d617e6a23fdc0ce05
